# Generated by Django 4.2.6 on 2023-11-25 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_recentnew'),
    ]

    operations = [
        migrations.AddField(
            model_name='recentnew',
            name='fields',
            field=models.CharField(default=0, max_length=2),
        ),
    ]
