# Generated by Django 4.2.6 on 2023-11-25 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_recentnew_fields'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RecentNew',
        ),
    ]
