# Generated by Django 4.2.6 on 2023-11-25 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_delete_recentnew'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecentNew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=3309)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
