# Generated by Django 4.2.6 on 2023-11-25 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_recentnew'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recentnew',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
