# Generated by Django 4.2.6 on 2023-11-26 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_profile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('Мужчина', 'Male'), ('Женщина', 'Female')], default='Женщина', max_length=8),
        ),
    ]
