# Generated by Django 4.2.6 on 2023-11-26 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_profile_attends_profile_comments_profile_elo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='votes',
            new_name='reports',
        ),
    ]
