# Generated by Django 4.2.6 on 2023-11-26 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_rename_votes_profile_reports'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='attends',
            new_name='votes',
        ),
    ]
