# Generated by Django 4.2.6 on 2023-11-26 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonpost',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
