# Generated by Django 4.2.6 on 2023-11-24 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('citizen', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='citreport',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='city_of_citizen_report', to='users.city'),
        ),
        migrations.AddField(
            model_name='citreport',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cit_report_status', to='citizen.reportstatus'),
        ),
        migrations.AddField(
            model_name='citreport',
            name='type_of_problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_of_problem', to='citizen.reportproblems'),
        ),
    ]
