# Generated by Django 4.2.6 on 2023-11-25 06:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('citizen', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='citreport',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='author_of_cit_report', to=settings.AUTH_USER_MODEL),
        ),
    ]
