# Generated by Django 4.2.6 on 2023-11-25 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizen', '0003_citreport_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citreport',
            name='comment',
            field=models.CharField(blank=True, default=None, max_length=1000),
        ),
    ]
