# Generated by Django 4.2.6 on 2023-11-24 21:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
        ('municipal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='munic_works',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='munic_work_creater', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='munic_works',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='city_of_munic_works', to='users.city'),
        ),
        migrations.AddField(
            model_name='munic_works',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_of_municip_works', to='municipal.type_of_munic_works'),
        ),
    ]
