# Generated by Django 4.2.6 on 2023-11-24 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('municipal', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('is_finished', models.BooleanField(default=False)),
                ('start_time', models.DateField(auto_now_add=True)),
                ('winner', models.CharField(blank=True, default=' ', max_length=30)),
                ('city', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='city_of_poll', to='users.city')),
            ],
        ),
        migrations.CreateModel(
            name='Poll_Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('count', models.PositiveIntegerField(default=0)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poll_option', to='municipal.poll')),
            ],
        ),
    ]
