# Generated by Django 4.2.6 on 2023-11-25 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('municipal', '0004_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='image',
            field=models.ImageField(default='', upload_to='polls_images'),
        ),
    ]
