# Generated by Django 4.2.6 on 2023-11-25 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('municipal', '0005_poll_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='logo',
            field=models.ImageField(default='', upload_to='polls_images'),
        ),
    ]
