# Generated by Django 4.2.6 on 2023-11-26 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('municipal', '0006_poll_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='munic_works',
            name='opt_image',
            field=models.ImageField(blank=True, default='123.png', upload_to='munic_works_schedule_photos'),
        ),
    ]
