# Generated by Django 4.2.6 on 2023-11-26 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('municipal', '0007_alter_munic_works_opt_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
